# Generated by Django 3.0.4 on 2020-04-11 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular file across whole server', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Filename', max_length=100)),
                ('extension', models.CharField(help_text='Extension', max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'date'],
            },
        ),
    ]
