# Generated by Django 3.0.4 on 2020-04-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['title']},
        ),
    ]
